openapi: 3.0.3

info:
  title: OpenRemit API
  version: 1.0.0
  description: OpenRemit Push API Specifications

servers:
  - url: https://sandbox.paysyslabs.com/openRemit
    variables:
      scheme:
        default: https
      host:
        default: sandbox.paysyslabs.com/OpenRemit  # Use the environment variable for host
      port:
        default: "443"  # Standard HTTPS port

paths:

  /api/v1/authenticate:
    post:
      summary: Authentication
      description: The service allows a partner to authenticate based on the credentials provided.
      operationId: authenticatePartner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username for the authentication.
                password:
                  type: string
                  description: Password for the authentication.
                channel:
                  type: string
                  description: Channel for the authentication (e.g., Web, Mobile).
              required:
                - username
                - password
                - channel
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    example: "00"
                  responseDescription:
                    type: string
                    example: "Processed OK"
                  expiry:
                    type: string
                    example: "1742798473"
                    description: "Unix timestamp in seconds representing the JWT token expiry time."
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmwiLCJpYXQiOjE3NDI3OTc4NzMsImV4cCI6MTc0Mjc5ODQ3MywiYXVkIjoiQ2FsbENlbnRlciJ9.017ixz4pUYCyISYYRl_iweWfQOe7YrjVPyo_hDY7KYf4JE06tht2pNEipMgY8aCU-UGK3xX037c6-zfDFrro0Q"
                    description: "The generated JWT access token used for authenticating subsequent requests."
        '401':
          description: Unauthorized - Wrong Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    example: "401"
                  responseDescription:
                    type: string
                    example: "Unauthorized – Wrong Credentials"


  /api/v1/paysyslabs/titlefetch:
    post:
      summary: Title Fetch
      description: Validates the beneficiary account/IBAN and returns the beneficiary's name.
      operationId: titleFetch
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requestId:
                  type: string
                  description: "Unique request reference"
                  example: "TFX20251209000001120"
                partnerReference:
                  type: string
                  description: "Partner's unique reference"
                  example: "PSL000000001"
                payoutMethod:
                  type: string
                  description: "Must be 'ACCOUNT'"
                  example: "ACCOUNT"
                senderCountry:
                  type: string
                  description: "Country of the sender"
                  example: "SA"
                bank:
                  type: object
                  properties:
                    bankCode:
                      type: string
                      description: "6-digit IMD"
                      example: "110001"
                    bankBranchCode:
                      type: string
                      description: "Bank branch code (optional)"
                      example: null
                    bankName:
                      type: string
                      description: "Bank name (optional)"
                      example: null
                    bankBranchName:
                      type: string
                      description: "Bank branch name (optional)"
                      example: null
                beneficiary:
                  type: object
                  properties:
                    idType:
                      type: string
                      description: "National ID or Passport"
                      example: "CNIC"
                    idNumber:
                      type: string
                      description: "ID number"
                      example: "4210112345671"
                    idIssuingCountry:
                      type: string
                      description: "Issuing country of the ID"
                      example: "PK"
                    mobileNo:
                      type: string
                      description: "Mobile number with country code"
                      example: "+923001234567"
                    accountNumber:
                      type: string
                      description: "IBAN or account number"
                      example: "00001234567890"
                transactionDetails:
                  type: object
                  properties:
                    amount:
                      type: string
                      description: "Transaction amount"
                      example: "10000.00"
                    currency:
                      type: string
                      description: "Currency of the transaction"
                      example: "PKR"
                    purposeOfPayment:
                      type: string
                      description: "Purpose of the payment"
                      example: "FAMILY_SUPPORT"
              required:
                - requestId
                - partnerReference
                - payoutMethod
                - bank
                - beneficiary
                - transactionDetails
      responses:
        '200':
          description: Title fetch successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    example: "00"
                  responseDescription:
                    type: string
                    example: "Title fetch successful"
                  requestId:
                    type: string
                    example: "TFX20251209000001120"
                  partnerReference:
                    type: string
                    example: "PSL000000001"
                  beneficiaryName:
                    type: string
                    example: "MUHAMMAD AHMED"
                  bank:
                    type: object
                    properties:
                      bankCode:
                        type: string
                        example: "110001"
                      bankBranchCode:
                        type: string
                        example: "0010"
                      bankName:
                        type: string
                        example: null
                      bankBranchName:
                        type: string
                        example: null
        '99':
          description: Account not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    example: "99"
                  responseDescription:
                    type: string
                    example: "Account not found"
                  requestId:
                    type: string
                    example: "TFX20251209000001120"
                  partnerReference:
                    type: string
                    example: "PSL000000001"

  /api/v1/paysyslabs/posttransactions:
    post:
      summary: Post Transactions Bulk
      description: Submits bulk remittance transactions for processing.
      parameters:
        - in: header
          name: X-Auth-Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Transaction submission response
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                  responseDescription:
                    type: string

  /api/v1/paysyslabs/transactionInquiry:
    post:
      summary: Transaction Inquiry
      description: Retrieves the status of a previously submitted transaction.
      parameters:
        - in: header
          name: X-Auth-Token
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Transaction inquiry response
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                  responseDescription:
                    type: string
                  transactionStatus:
                    type: string

  /api/v1/paysyslabs/balanceInquiry:
    post:
      summary: Balance Inquiry
      description: Returns the available settlement account balance of the partner.
      parameters:
        - in: header
          name: X-Auth-Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Balance inquiry response
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                  responseDescription:
                    type: string
                  availableBalance:
                    type: number

  /api/v1/paysyslabs/get/participant/imd:
    get:
      summary: Get Participant IMD List
      description: Returns the list of participating banks with IMD and BIC information.
      parameters:
        - in: header
          name: X-Auth-Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: IMD list response
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                  responseDescription:
                    type: string


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Indicates that the Bearer token will be a JWT (JSON Web Token)
  schemas:
    AuthenticationResponse:
      type: object
      properties:
        responseCode:
          type: string
          description: "Standard response code. '00' indicates successful processing."
        responseDescription:
          type: string
          description: "Description of the response."
        expiry:
          type: string
          description: "Unix timestamp in seconds (since 1970-01-01T00:00:00Z UTC). Represents the JWT token expiry time."
        token:
          type: string
          description: "The generated JWT access token used for authenticating subsequent requests."
      required:
        - responseCode
        - responseDescription
        - expiry
        - token
    
    TitleFetchResponse:
      type: object
      properties:
        responseCode:
          type: string
          description: "Standard response code."
        responseDescription:
          type: string
          description: "Describes the response."
        requestId:
          type: string
          description: "Unique request reference."
        partnerReference:
          type: string
          description: "Partner's reference."
        beneficiaryName:
          type: string
          description: "The beneficiary's name."
        bank:
          type: object
          properties:
            bankCode:
              type: string
              description: "Bank's IMD."
            bankBranchCode:
              type: string
              description: "Bank branch code (optional)."
            bankName:
              type: string
              description: "Bank name."
            bankBranchName:
              type: string
              description: "Bank branch name."
      required:
        - responseCode
        - responseDescription
        - requestId
        - partnerReference
        - beneficiaryName
        - bank